# サイトの基本情報
site_name: My Awesome Project Docs  # サイトタイトル（ブラウザのタブやヘッダーに表示）
site_url: https://example.com/     # 任意: サイトの公開URL

# Materialテーマの有効化
theme:
    name: material
    features:
      - navigation.tabs      # ← これでメインメニューがトップバー（上部）に移動します
      - navigation.sections  # (任意) セクション構造をより見やすくします
      - toc.integrate        # ← これで右側の目次が消え、左側のサイドバーに統合されます
      # windmillだとmermaidが表示されない
    # name: windmill
    
    # 言語を日本語に設定（サイト内の日付や検索などのUIが日本語になります）
    language: ja

# cssの適用
extra_css:
  - assets/stylesheets/custom.css

# ナビゲーション（目次）の定義
nav:
    - ホーム: index.md             # docs/index.md に対応
    - 使い方ガイド:                 # トップレベルの見出し (親)
        - はじめる: sample_dir/test.md
        - marpテスト: sample_dir/include_marp.md

markdown_extensions:
  # コードブロックの拡張機能（ネスト対応やカスタム処理を可能にする）
  - pymdownx.superfences:
      # カスタムコードブロック (フェンス) の定義
      custom_fences:
        # Mermaid図のレンダリング設定
        - name: mermaid
          class: mermaid
          # Mermaidの定義コードをそのままHTMLに出力するためのフォーマット指定
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  # プラグインの有効化
  - search:
      # 検索機能の言語設定を日本語に
      lang: ja

# marpスライドのルートディレクトリを固定できる
# extra_files:
#   - 'slides/slide.html'